

INSERT INTO `permissions` (`id`, `name`, `description`) VALUES
(1, 'add_product', 'Add Product'),
(2, 'edit_product', 'Edit Product'),
(3, 'delete_product', 'Delete Product'),
(4, 'add_user', 'Add new User'),
(5, 'edit_user', 'Edit User'),
(6, 'list_products', 'List Products'),
(7, 'list_users', 'List Users'),
(8, 'add_customer', 'Add new Customer'),
(9, 'edit_customer', 'Edit Customer'),
(10, 'delete_customer', 'Delete Customer'),
(11, 'list_customers', 'List Customers'),
(12, 'list_suppliers', 'List Suppliers'),
(13, 'add_supplier', 'Add Supplier'),
(14, 'edit_supplier', 'Edit_Supplier'),
(15, 'delete_supplier', 'Delete Supplier'),
(16, 'manage_people', 'Manage People'),
(17, 'manage_products', 'Manage Products'),
(18, 'manage_shops', 'Manage Shops'),
(19, 'add_shop', 'Add_shop'),
(20, 'list_shops', 'List_shops'),
(21, 'edit_shop', 'Edit Shops'),
(22, 'delete_shop', 'Delete Shop'),
(23, 'view_report', 'View Reports'),
(24, 'product_report', 'View Product Report'),
(25, 'sale_report', 'View Sale Report'),
(26, 'purchase_report', 'View Purchase Report'),
(27, 'product_sale_report', 'View Product Sale Report in Details'),
(28, 'product_combined_report', 'View Product Sale & Purchase Reports in Details'),
(29, 'product_purchase_report', 'View Product Purchase Report in Details'),
(30, 'manage_sale', 'Manage Sales'),
(31, 'add_sale', 'Add new sale'),
(32, 'edit_sale', 'Edit Sale'),
(33, 'delete_sale', 'Delete Sale'),
(34, 'list_sales', 'List Sales'),
(35, 'add_sale_payment', 'Add Sale Payment'),
(36, 'view_sale_payment', 'View Sale Payments'),
(37, 'edit_sale_payment', 'Edit Sale Payment'),
(38, 'delete_sale_payment', 'Delete Sale Payment'),
(39, 'print_sale_payment', 'Print Sale Payment'),
(40, 'print_sale', 'Print Sale'),
(41, 'manage_purchase', 'Manage purchases'),
(42, 'add_purchase', 'Add new purchase'),
(43, 'edit_purchase', 'Edit purchase'),
(44, 'delete_purchase', 'Delete purchase'),
(45, 'list_purchases', 'List purchases'),
(46, 'add_purchase_payment', 'Add purchase Payment'),
(47, 'view_purchase_payment', 'View purchase Payments'),
(48, 'edit_purchase_payment', 'Edit purchase Payment'),
(49, 'delete_purchase_payment', 'Delete purchase Payment'),
(50, 'print_purchase_payment', 'Print purchase Payment'),
(51, 'print_purchase', 'Print Purchase '),
(52, 'manage_setting', 'Manage System Settings'),
(53, 'user_permission', 'Manage User Permission');