
INSERT INTO `permissions` (`id`, `name`, `description`, `created_at`, `updated_at`, `deleted_at`) VALUES
(1, 'add_product', 'Add Product', NULL, NULL, NULL),
(2, 'edit_product', 'Edit Product', NULL, NULL, NULL),
(3, 'delete_product', 'Delete Product', NULL, NULL, NULL),
(4, 'add_user', 'Add new User', NULL, NULL, NULL),
(5, 'edit_user', 'Edit User', NULL, NULL, NULL),
(6, 'list_products', 'List Products', NULL, NULL, NULL),
(7, 'list_users', 'List Users', NULL, NULL, NULL),
(8, 'add_customer', 'Add new Customer', NULL, NULL, NULL),
(9, 'edit_customer', 'Edit Customer', NULL, NULL, NULL),
(10, 'delete_customer', 'Delete Customer', NULL, NULL, NULL),
(11, 'list_customers', 'List Customers', NULL, NULL, NULL),
(12, 'list_suppliers', 'List Suppliers', NULL, NULL, NULL),
(13, 'add_supplier', 'Add Supplier', NULL, NULL, NULL),
(14, 'edit_supplier', 'Edit_Supplier', NULL, NULL, NULL),
(15, 'delete_supplier', 'Delete Supplier', NULL, NULL, NULL),
(16, 'manage_people', 'Manage People', NULL, NULL, NULL),
(17, 'manage_products', 'Manage Products', NULL, NULL, NULL),
(18, 'manage_shops', 'Manage Shops', NULL, NULL, NULL),
(19, 'add_shop', 'Add_shop', NULL, NULL, NULL),
(20, 'list_shops', 'List_shops', NULL, NULL, NULL),
(21, 'edit_shop', 'Edit Shops', NULL, NULL, NULL),
(22, 'delete_shop', 'Delete Shop', NULL, NULL, NULL),
(23, 'view_report', 'View Reports', NULL, NULL, NULL),
(24, 'product_report', 'View Product Report', NULL, NULL, NULL),
(25, 'sale_report', 'View Sale Report', NULL, NULL, NULL),
(26, 'purchase_report', 'View Purchase Report', NULL, NULL, NULL),
(27, 'product_sale_report', 'View Product Sale Report in Details', NULL, NULL, NULL),
(28, 'product_combined_report', 'View Product Sale & Purchase Reports in Details', NULL, NULL, NULL),
(29, 'product_purchase_report', 'View Product Purchase Report in Details', NULL, NULL, NULL),
(30, 'manage_sale', 'Manage Sales', NULL, NULL, NULL),
(31, 'add_sale', 'Add new sale', NULL, NULL, NULL),
(32, 'edit_sale', 'Edit Sale', NULL, NULL, NULL),
(33, 'delete_sale', 'Delete Sale', NULL, NULL, NULL),
(34, 'list_sales', 'List Sales', NULL, NULL, NULL),
(35, 'add_sale_payment', 'Add Sale Payment', NULL, NULL, NULL),
(36, 'view_sale_payment', 'View Sale Payments', NULL, NULL, NULL),
(37, 'edit_sale_payment', 'Edit Sale Payment', NULL, NULL, NULL),
(38, 'delete_sale_payment', 'Delete Sale Payment', NULL, NULL, NULL),
(39, 'print_sale_payment', 'Print Sale Payment', NULL, NULL, NULL),
(40, 'print_sale', 'Print Sale', NULL, NULL, NULL),
(41, 'manage_purchase', 'Manage purchases', NULL, NULL, NULL),
(42, 'add_purchase', 'Add new purchase', NULL, NULL, NULL),
(43, 'edit_purchase', 'Edit purchase', NULL, NULL, NULL),
(44, 'delete_purchase', 'Delete purchase', NULL, NULL, NULL),
(45, 'list_purchases', 'List purchases', NULL, NULL, NULL),
(46, 'add_purchase_payment', 'Add purchase Payment', NULL, NULL, NULL),
(47, 'view_purchase_payment', 'View purchase Payments', NULL, NULL, NULL),
(48, 'edit_purchase_payment', 'Edit purchase Payment', NULL, NULL, NULL),
(49, 'delete_purchase_payment', 'Delete purchase Payment', NULL, NULL, NULL),
(50, 'print_purchase_payment', 'Print purchase Payment', NULL, NULL, NULL),
(51, 'print_purchase', 'Print Purchase ', NULL, NULL, NULL),
(52, 'manage_setting', 'Manage System Settings', NULL, NULL, NULL),
(53, 'user_permission', 'Manage User Permission', NULL, NULL, NULL),
(54, 'view_sale', 'View Sale Details', NULL, NULL, NULL),
(55, 'view_purchase', 'View Purchase Details', NULL, NULL, NULL),
(56, 'manage_trash', 'manage deleted items', NULL, NULL, NULL);
